version: '3'

services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ../../page-generator:/usr/src/app
    command: sh -c 'yarn dev'
    ports:
      - '3000:3000'
    tty: true

