version: '3'

services:
  react:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd react && yarn && yarn start'
    ports:
      - '3000:3000'
    tty: true

